services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: fajar_user
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: notes_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PORT=8000
    env_file:
      - .env
    volumes:
      - .:/app  # This is the "Magic" volume that syncs your village laptop and the container

volumes:
  pgdata: # Now this is at the correct level