"""added index to user_id and delete_at

Revision ID: 025f97f5a66a
Revises: 675df898b8e9
Create Date: 2026-04-24 03:27:10.015739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '025f97f5a66a'
down_revision: Union[str, Sequence[str], None] = '675df898b8e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Notes_delete_at'), 'Notes', ['delete_at'], unique=False)
    op.create_index(op.f('ix_Notes_user_id'), 'Notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Notes_user_id'), table_name='Notes')
    op.drop_index(op.f('ix_Notes_delete_at'), table_name='Notes')
    # ### end Alembic commands ###
