"""Add deleted_at to Notes

Revision ID: 675df898b8e9
Revises: 6b0bcc087ad5
Create Date: 2026-04-24 01:54:00.717246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675df898b8e9'
down_revision: Union[str, Sequence[str], None] = '6b0bcc087ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Notes', sa.Column('delete_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Notes', 'delete_at')
    # ### end Alembic commands ###
