"""Add is_active to Users

Revision ID: 6b0bcc087ad5
Revises: 8a3e8045db97
Create Date: 2026-04-23 05:35:04.665512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b0bcc087ad5'
down_revision: Union[str, Sequence[str], None] = '8a3e8045db97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
  

    op.add_column('Users', sa.Column('is_active', sa.Boolean(), nullable=True))
    
    # 2. Give everyone the "Hat" (The "Fill")
    # CRITICAL: Use 'Users' (Capital U) to match your table name!
    op.execute("UPDATE \"Users\" SET is_active = True")
    
    # 3. Seal it so no future user can be NULL (The "Seal")
    op.alter_column('Users', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'is_active')
    # ### end Alembic commands ###
